#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

wanted_branch="master"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ $current_branch != $wanted_branch ]];
then
    echo "cannot deploy branch: ${current_branch} to production (must be ${wanted_branch})" 1>&2
    exit 1
fi

export GOMAXPROCS=1
hugo
DEST="$HOME/public_html"
SOURCE="$(pwd)/public"

current_release="$(git describe --long --dirty --always)"
echo "${current_release}" > "public/release.txt"

echo "deploying ${current_release} $(pwd) -> ${DEST}"

rm -rf "${SOURCE:?}"/*
cp -ruv "${SOURCE:?}"/* "${DEST}"

cowsay "deployed ${current_release} successfully"
