#!/bin/bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

wanted_branch="master"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ $current_branch != $wanted_branch ]];
then
    echo "cannot deploy branch: ${current_branch} to production (must be ${wanted_branch})" 1>&2
    exit 1
fi

hugo
DEST="/www"
SOURCE="$(pwd)/public"

current_release="$(git describe --long --dirty --always)"
echo "${current_release}" > "public/release.txt"

echo "deploying ${current_release} $(pwd) -> ${DEST}"

cp -ruv "${SOURCE}"/* "${DEST}"

cowsay "deployed ${current_release} successfully"
